
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // Use a fallback during build, actual DATABASE_URL will be used at runtime
    url: env("DATABASE_URL") || "postgresql://placeholder:placeholder@localhost:5432/placeholder",
  },
});
